# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "An open-source, frictionless and secure way to share and manage app secrets across teams."
  homepage "https://envless.dev"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Darwin_x86_64.tar.gz"
      sha256 "094389999cdca3ef190812a65fc9778816b057bcd0b65d45a0dfbdd9570fe665"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Darwin_arm64.tar.gz"
      sha256 "cf7635e006e58b4295940f9b9f7d30ff56ca9e26838116ce0b48527767efdbbf"

      def install
        bin.install "cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Linux_arm64.tar.gz"
      sha256 "063b80e528c00912b2b5f73249d54f5c1ed2de09e53fff680c039bcabd2143c8"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Linux_x86_64.tar.gz"
      sha256 "3548b4899188de7e2b7e233920078bf2da7c1495695268999d68af7abf126c41"

      def install
        bin.install "cli"
      end
    end
  end
end
