# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "An open-source, frictionless and secure way to share and manage app secrets across teams."
  homepage "https://envless.dev"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Darwin_x86_64.tar.gz"
      sha256 "27ea4a25cf3a23823a78a769c13b8f5f3043fbfca50e2162c48907d81ba46038"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Darwin_arm64.tar.gz"
      sha256 "ec44802810004f806aeb6989c2696f03fd0c56e3937a37a3caaf34f6251e06b0"

      def install
        bin.install "cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Linux_x86_64.tar.gz"
      sha256 "6682faffc2855553ec116d1549172dd8444e77bdf47a22e4b6ce0959c3c656c2"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/envless/cli/releases/download/0.0.2/cli_Linux_arm64.tar.gz"
      sha256 "d7724e39d34b6279af95c7b7f32c20ed3c81648155eef3090246cc094cdf6456"

      def install
        bin.install "cli"
      end
    end
  end
end
